server:
  port: 9191
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oAuthDB?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: ChangeMe
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      properties:
        hibernate:
          show-sql: true
          format-sql: true
logging:
  level:
    org:
      hibernate:
        type: trace